# -*- coding: utf-8 -*-
"""column.2c.weba Using Random forest algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-eVkC1m8dCTBo8fDArfNJ29cryRrGfGJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/column_2C_weka.csv')

df.head(20)

df.tail(10)

df.shape

df.info(10)

df.describe()

a=df['class']
plt.plot(a)

b=df['lumbar_lordosis_angle']
c=df['degree_spondylolisthesis']
plt.scatter(b,c)

d=df['sacral_slope']
plt.hist(d)

e=df['lumbar_lordosis_angle']
plt.bar(e,height=100,width=100)

r=df['pelvic_incidence']
plt.pie(r)

A=df['lumbar_lordosis_angle']
B=df['pelvic_tilt numeric']
sns.lineplot(x=A,y=B,data=df)

C=df['class']
D=df['lumbar_lordosis_angle']
sns.scatterplot(x=C,y=D,data=df)

E=df['pelvic_incidence']
F=df['lumbar_lordosis_angle']
sns.barplot(x=E,y=F,data=df)

sns.countplot(x='class',data=df)

sns.pairplot(df,hue='class')

x=[23,67,45,23,67]
y=[10,20,30,40,50]
sns.distplot(x,y)

df.isnull().sum()

x=df['lumbar_lordosis_angle']
sns.boxplot(x)

x=df.drop('class',axis=1)
x

y=df['class']
y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

x_train.shape

x_test.shape

from sklearn.preprocessing import StandardScaler

std=StandardScaler()

s=std.fit_transform(x_train)
s

from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier()

clf.fit(x_train,y_train)

pred=clf.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(pred,y_test)

from sklearn.metrics import confusion_matrix

confusion_matrix(pred,y_test)